config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :user do
    collection do
      get :login
      post :login
      get :sign_up
      post :sign_up
      get :logout
      get :dashboard
      get :resend_otp
      get :forgot_password
      post :forgot_password
      patch :forgot_password
      post :register_as_seller
      get :register_as_seller
      patch :register_as_seller
      get :complete_signup
      patch :complete_signup
    end
  end

  resources :products do
    collection do
      get :sell_art
    end
  end

  constraints subdomain: 'admin' do
    get '/', to: 'arts#index'
  end

  root 'arts#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_detail, dependent: :destroy
  has_many :products
  delegate :full_name, :phone_no, to: :user_detail, allow_nil: true
  
  attr_accessor :password, :confirm_password, :dont_validate_password
  validates_presence_of :email_id
  validates_presence_of :password, if: Proc.new{|user| user.dont_validate_password != false}
  validates_presence_of :confirm_password, if: Proc.new{|user| user.new_record?}
  validate :password_match, if: Proc.new{|user| user.password.present?}
  validates :email_id, uniqueness: { scope: :is_active,
      message: "can have only one active per time." }, if: Proc.new{|user| user.new_record?} #:phone_no
  before_save :hash_password, if: Proc.new{|user| user.dont_validate_password != false}
   
  scope :active, -> { where(is_active: true) }
  
  
  def authenticate
    user = User.active.where("email_id = ?", self.email_id).first
    if user.present?
      return user.hashed_password == Digest::SHA1.hexdigest(user.password_salt.to_s + self.password)
    end
    return false
  end
  
  def send_otp_by_mail(otp)
    UserMailer.with(user: self, otp: otp).send_otp.deliver_now
  end
  
  def send_password_reset_token_by_mail
    if self.update(reset_password_token: SecureRandom.base64(17).gsub(/[+, =, \/]/,""), dont_validate_password: false)
      UserMailer.with(user: self).send_password_reset_token.deliver_now
    end
  end
  
  def self.minimum_password_length
    false
  end
  
  private
  
    def password_match
      if password != confirm_password
        errors.add(:password, "doesn't match")
      end
    end
    
    def hash_password
      self.password_salt =  SecureRandom.base64(8) if self.password_salt == nil
      self.hashed_password = Digest::SHA1.hexdigest(self.password_salt + self.password)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :login_required, only: [:login, :sign_up, :resend_otp, :forgot_password]
  before_action :redirect_to_root, only: [:login, :sign_up, :resend_otp, :forgot_password]
  skip_before_action :check_first_login, only: [:complete_signup]
  
  def login
    @user = User.new
    if request.post?
      @user = User.new(user_params)
      if @user.authenticate
        user = User.active.where("email_id = ?", @user.email_id).first
        user.update(sign_in_count: user.sign_in_count.to_i + 1, dont_validate_password: false)
        session[:user_id] = user.id
        reset_flash_message
        redirect_to (session[:back_path].present? ? session.delete(:back_path) : root_path)
      else
        reset_flash_message
        flash[:danger] = t(:wrong_credentials)
        redirect_to action: :login
      end
    end
  end
  
  def sign_up
    reset_flash_message
    @user = User.new
    if request.post?
      @user = User.new(user_params) 
      check_user_exists = User.find_by_email_id(@user.email_id).present?
      unless check_user_exists
        unless params[:step].present?
          sent_otp
          @step = :otp_send
        else
          otp = params[:otp].values.join
          if session[:otp]["code"] == otp
            if @user.save
              session[:otp] = nil
              session[:user_id] = @user.id
              redirect_to :root
            else
              @time = (120 - (Time.now.to_time - session[:otp]["sent_time"].to_time)).to_i
              @step = "password_not_match"
              render action: :sign_up
            end
          else
            @time = (120 - (Time.now.to_time - session[:otp]["sent_time"].to_time)).to_i
            flash[:danger] = t(:wrong_otp)
            @step = :otp_send
            render action: :sign_up
          end
        end
      else
        flash[:danger] = "#{t(:account_exist)}. <br>#{view_context.link_to t(:click_here_to_login), login_user_index_path} or #{view_context.link_to t(:click_hereh_to_reset_password), forgot_password_user_index_path}"
        redirect_to action: :sign_up
      end
    else
      session[:otp] = {}
    end
  end
  
  def resend_otp
    sent_otp
    respond_to :js
  end
  
  def sent_otp
    session[:otp] = {} if session[:otp].nil?
    time_diff = Time.now.to_time - session[:otp]["sent_time"].to_time if session[:otp]["sent_time"].present?
    @time = 120 - time_diff.to_i
    if !(session[:otp]["sent_time"].present?) || time_diff.to_i > 120
      session[:otp]["code"] = rand.to_s[2..5]
      session[:otp]["sent_time"] = Time.now
      @user = User.new(email_id: params[:email_id]) unless @user.present?
      @user.send_otp_by_mail(session[:otp]["code"])
      @time = (120 - (Time.now.to_time - session[:otp]["sent_time"].to_time)).to_i
    end
  end
  
  def complete_signup
    reset_flash_message
    unless @current_user.user_detail
      if request.patch?
        @user_detail = @current_user.build_user_detail(user_params[:user_detail])
        email_check = user_params[:email_id] == @current_user.email_id
        if email_check && @user_detail.save
          flash[:success] = t(:signup_completed)
          redirect_to :root
        end
      end
    else
      redirect_to :root
    end
  end
  
  def logout
    reset_session
    redirect_to :root
  end
  
  def forgot_password
    @user = User.new
    if request.post?
      @user = User.find_by_email_id(user_params[:email_id])
      if @user.present?
        @user.send_password_reset_token_by_mail
        @step = :mail_sent
        reset_flash_message
        flash[:success] = t(:sent_by_mail)
      else
        reset_flash_message
        flash[:danger] = t(:user_not_found)
        redirect_to action: :forgot_password
      end
    elsif request.patch?
      @user = User.find_by_email_id(user_params[:email_id])
      if @user.update(user_params)
        reset_password_token
        reset_flash_message
        flash[:danger] = t(:password_changed)
        redirect_to :root
      else
        @step = :password_not_match
        render action: :forgot_password
      end
    else
      if params[:reset_password_token].present?
        @user = User.find_by_reset_password_token(params[:reset_password_token])
        if @user.present?
          @step = :token_authenticated
        else
          reset_flash_message
          flash[:danger] = t(:user_not_found)
          redirect_to action: :forgot_password
        end
      end
    end
  end
  
  def dashboard
    reset_flash_message
    @user_detail = @current_user.user_detail
  end

  def edit
  end

  def register_as_seller
    reset_flash_message
    unless @current_user.is_seller
      @user_detail = @current_user.user_detail
      if request.patch?
        user = User.new(user_params.except(:user_detail))
        if user.authenticate
          if user.email_id == @current_user.email_id
            if @user_detail.update(user_params[:user_detail])
              @current_user.update(is_seller: true, dont_validate_password: false)
              flash[:success] = t(:registered_as_seller)
            end
          end
        else
          @error = true
          flash[:danger] = t(:wrong_credentials)
        end
      end
    else
      flash[:danger] = t(:already_registered_as_seller)
      redirect_to :new_product
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:password, :confirm_password, :email_id, :phone_no, 
        user_detail: [:full_name, :phone_no])
    end
    
    def reset_session
      session[:user_id] = nil
    end
    
    def redirect_to_root
      if session[:user_id].present?
        redirect_to :root
      end
    end
    
    def reset_password_token
      @user.update(reset_password_token: nil, reset_password_sent_at: nil, dont_validate_password: false)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_error_messages.html.erb
<% if user && user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: "layouts/flash_messages" %>

app/views/user/_registration.html.erb
<div class="container register-sell-art">
  <div class="row">
    <div class="col-4">
      <%= image_tag "artist-illustration.jpg", size: "300"%>
    </div>
    <div class="col-8">
      <p class="title"> REGISTER TO SELL ART ON GET ART </p>
      <p class="create-desc"> How to sell Art on Get Art </p>
      <%= form_for(@current_user, url: register_as_seller_user_index_path, html: {remote: true}) do |f| %>
        <%= flash_messages %>
        <%= f.hidden_field :email_id %>
        <div class="form-group row">
          <%= f.label 'Email', class: "col-sm-3 col-form-label" %><br>
          <%= text_field_tag :email_id, @current_user.email_id, 
              class: "form-control col-sm-9", required: true, disabled: true %>
        </div>
        <%= f.fields_for :user_detail, @user_detail do |ff|%>
          <div class="form-group row">
            <%= ff.label 'Full Name', class: "col-sm-3 col-form-label" %><br>
            <%= ff.text_field :full_name, class: "form-control col-sm-9",
                required: false %>
          </div>
          
          <div class="form-group row">
            <%= ff.label 'Phone Number' ,class: "col-sm-3 col-form-label" %><br>
            <%= ff.text_field :phone_no, class: "form-control col-sm-9", 
                required: true %>
          </div>
        <% end %>
        
        <div class="form-group row">
          <%= f.label 'Current Password', class: "col-sm-3 col-form-label" %><br>
          <%= f.password_field :password, autocomplete: "current-password",
              placeholder: "Enter Password", required: true, 
              class: "form-control col-sm-9" %>
        </div>
        <div class="row">
          <div class="col-10">
            <p> Confirm Get Art credential to register </p> 
          </div>
          <div class="col-2">
            <%= f.submit "Confirm", class: "btn btn-lg btn-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/_seller_created_successfully.html.erb
<div class="container seller-registered">
<div class="row">
  <div class='congratulate'> Congratulations </div>
</div>
<div class="row">
  <div class="title art-sell"> YOU ARE GET ART SELLER NOW </div>
</div>
<div class="sell-art-button-center">
  <%= button_to "SELL ART", new_product_path, method: :get, class: "sell-art-button" %>
</div>
<div class="row register-footer">

  <div class="col-3">
    Legal side of sale
  </div>
  <div class="col-3">
    Payment
  </div>
  <div class="col-3">
    Shipping of art
  </div>
  <div class="col-3">
    More about selling art on get Art
  </div>
  
</div>


</div>

app/views/user/complete_signup.html.erb
<div class="signin-box">
  <div class="row login-background">
    <div class="col-5">
    </div>
    <div class="col-7 login-field complete-signup-field">
      <h2 class="dark-red">COMPLETE SIGN UP</h2>
      <p>Sign Up to shop and explore Get Art</p>
      <%= form_for(@current_user, url: complete_signup_user_index_path) do |f| %>
        <%= render partial: "error_messages", locals:{ user:  @user_detail} %>
        <%= f.fields_for :user_detail, @current_user.build_user_detail do |user_detail|%>
          <div class="field">
            <%= user_detail.label :email_id, "E-mail:" %>
            <%= text_field_tag :email_id, @current_user.email_id, disabled: true %>
          </div>
          <div class="field">
            <%= user_detail.label :full_name, "Full Name:" %>
            <%= user_detail.text_field :full_name, autofocus: true, autocomplete: "off", placeholder: "Enter Your Full Name", required: true %>
          </div>
          <div class="field">
            <%= user_detail.label :phone_no, "Mobile Number:" %>
            <%= user_detail.text_field :phone_no, autocomplete: "off", placeholder: "Enter Your Mobile Number", required: true, class: "numberField" %>
          </div>  
        <% end %>
        <%= f.hidden_field :email_id %>
        <div class="field complete-signup-submit-field field-right">
          <%= f.submit "SAVE" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/dashboard.html.erb
<div class="grid-container">
  <div class="col-user-img">
    <div class="user-img-container grey-color-container">
      <div class="edit-container"><%= link_to "Edit", logout_user_index_path %></div>
      <div class="user-img">
        <%= image_tag @user_detail.avatar.url %>
      </div>
      <div class="name-container"><%= @user_detail.full_name.presence || "(Full Name)" %></div>
      <div class="email-container"><%= @user_detail.email_id %></div>
      <div class="phone-no-container"><%= @user_detail.phone_no.presence || "(Phone no.)" %></div>
      <div class="log-out-container"><%= link_to "Log out", logout_user_index_path %></div>
    </div>
  </div>
  <div class="user-actions-container">
    <%= link_to orders_path do %>
      <div class="user-action-container grey-color-container">
        <div class="action-img">
          <%= image_tag "my_orders.svg" %>
        </div>
        <div class="action-hreader-des">
          <h5>My Orders</h5>
          <p>Track Return Repeat buy</p>
        </div>
      </div>
    <% end %>
    <%= link_to addresses_path do %>
      <div class="user-action-container grey-color-container">
        <div class="action-img">
          <%= image_tag "my_addresses.svg" %>
        </div>
        <div class="action-hreader-des">
          <h5>Addresses</h5>
          <p>Add Edit Remove</p>
        </div>
      </div>
    <% end %>
    <%= link_to payments_path do %>
      <div class="user-action-container grey-color-container">
        <div class="action-img">
          <%= image_tag "payment_options.svg" %>
        </div>
        <div class="action-hreader-des">
          <h5>Payment Options</h5>
          <p>Add Edit Remove</p>
        </div>
      </div>
    <% end %>
    <%= link_to "#" do %>
      <div class="user-action-container grey-color-container">
        <div class="action-img">
          <%= image_tag "security.svg" %>
        </div>
        <div class="action-hreader-des">
          <h5>Security</h5>
          <p>Personal Details and Password</p>
        </div>
      </div>
    <% end %>
    <%= link_to coupons_path do %>
      <div class="user-action-container grey-color-container">
        <div class="action-img">
          <%= image_tag "coupons.svg" %>
        </div>
        <div class="action-hreader-des">
          <h5>Coupons</h5>
          <p>Manage Coupons</p>
        </div>
      </div>
    <% end %>
    <%= link_to help_index_path do %>
      <div class="user-action-container grey-color-container">
        <div class="action-img">
          <%= image_tag "help.svg" %>
        </div>
        <div class="action-hreader-des">
          <h5>Help</h5>
          <p>Get in touch with us</p>
        </div>
      </div>
    <% end %> 
  </div>
</div>

app/views/user/forgot_password.html.erb
<div class="signin-box">
  <div class="row login-background">
    <div class="col-5">
    </div>
    <div class="col-7 login-field">
      <h2 class="dark-red">RESET YOUR PASSWORD</h2>
      <%= form_for(@user, url: forgot_password_user_index_path) do |f| %>
        <%= render partial: "error_messages", locals:{ user: @user} %>
        <% case @step.try(:to_sym) %>
        <% when :mail_sent %>
        <% when :token_authenticated, :password_not_match %>
          <%= render partial: "error_messages", locals:{ user: @user} %>
          <div class="field">
            <% if User.minimum_password_length %>
              <em>(<%= User.minimum_password_length %> characters minimum)</em><br />
            <% end %>
            <%= f.password_field :password, autocomplete: "new-password", placeholder: "Set Password", required: true %>
          </div>

          <div class="field">
            <%= f.password_field :confirm_password, autocomplete: "new-password", placeholder: "Confirm Password", required: true %>
          </div>
          <%= f.hidden_field :email_id, readonly: true %>
          <%= hidden_field_tag :step, @step %>
          
          <div class="field field-right">
            <%= f.submit "CONTINUE" %>
          </div>
        <% else %>
          <div class="field">
            <%= f.email_field :email_id, autofocus: true, autocomplete: "off", placeholder: "E-mail", required: true %>
          </div>

          <div class="field field-right">
            <%= f.submit "CONTINUE" %>
          </div>
        <% end %>
        
        <div class="field field-center signup-link-margin">
          <%= link_to "New to Get Art? Create an Account", sign_up_user_index_path, class: "light-red bold-text" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/login.html.erb
<div class="signin-box">
  <div class="row login-background">
    <div class="col-5">
    </div>
    <div class="col-7 login-field">
      <h2 class="dark-red">LOGIN</h2>
      <p>Get safe access to your Get Art Account</p>
      <%= form_for(@user, url: login_user_index_path) do |f| %>
        <%= render partial: "error_messages", locals:{ user: @user} %>
        <div class="field">
          <%= f.email_field :email_id, autofocus: true, autocomplete: "off", placeholder: "E-mail", required: true %>
        </div>

        <div class="field">
          <%= f.password_field :password, autocomplete: "current-password", placeholder: "Enter Password", required: true %>
        </div>
        
        <div class="field field-right">
          <%= link_to "Forgot the password?", forgot_password_user_index_path, class: "forgot-password light-red" %>
        </div>

        <div class="field field-right">
          <%= f.submit "LOGIN" %>
        </div>
        
        <div class="field field-center signup-link-margin">
          <%= link_to "New to Get Art? Create an Account", sign_up_user_index_path, class: "light-red bold-text signup-link" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/register_as_seller.html.erb
<div id="seller-registration">
  <%= render partial: 'registration' %>
</div>

app/views/user/register_as_seller.js.erb
$('#seller-registration').html(`
  <% if @error.present? %>
    <%= render  "registration"%>
  <% else %>
    <%= render  "seller_created_successfully"%>
  <% end%>
`);

app/views/user/resend_otp.js.erb
var time_holder = document.getElementById("time-holder");
<% p @time %>
<% if @time > 0 && @time <= 120 %>
  <% sent_time_in_rails = (session[:otp]["sent_time"].present? ? session[:otp]["sent_time"].to_time : Time.now.to_time).to_s.slice(0, 19) %>  
  time_holder.innerHTML = `<%= t(:didnt_receive_the_code) %>? <%= t(:send_code_again_in) %><span id="sec-timer"><%= @time %></span> <%= t(:seconds) %>`;
  clearInterval(x);
  start('<%= sent_time_in_rails %>');
<% else %>
  console.log(11);
  time_holder.innerHTML = `<%= link_to t(:resend_otp), resend_otp_user_index_path, remote: true %>`;
  $(time_holder).find('a').attr("href", $(time_holder).find('a').attr("href") + "?email_id=" + $('#user_email_id').val());
<% end %>
$('#dummy-otp').val(<%= session[:otp]["code"] %>)

app/views/user/sign_up.html.erb
<div class="signup-box">
  <div class="row signup-background">
    <div class="col-5">
    </div>
    <div class="col-7 signup-field">
      <h2 class="dark-red">SIGN UP</h2>
      <p>Sign Up to shop and explore Get Art</p>
      <%= form_for(@user, url: sign_up_user_index_path, html: { onsubmit: "return validate(event)" }) do |f| %>
        <%= render partial: "error_messages", locals:{ user: @user} %>
        <% @step ||= :non %>
        <% button_name = (@step.to_sym == :otp_send || @step.to_sym == :password_not_match) ? "SIGN UP" : "CONTINUE" %>
        <% case @step.to_sym %>
        <% when :otp_send, :password_not_match %>
          <div class="field">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text left-input-group-text">Email :</span>
              </div>
              <%= text_field_tag :email_id, @user.email_id, disabled: true, class: "form-control email-shower" %>
              <div class="input-group-append">
                <span id="set-password-visibility" class="input-group-text right-input-group-text">
                  <%= link_to "Change?", sign_up_user_index_path, class: "light-red change-link" %>
                </span>
              </div>
            </div>
          </div>

          <div class="field">
            <div style="width:100%;">
              <p class="float-left otp-sent-label">OTP sent to E-mail</p>
              <p id="time-holder" class="otp-timer light-red float-right">
                <%#= t(:didnt_receive_the_code) %><!-- ? --> <%= t(:send_code_again_in) %>
                <span id="sec-timer"><%= @time %></span>  <%= t(:seconds) %>
              </p>
            </div>
          </div>
          
          <div class="field">
            <div class="width-100 otp-field-container">
              <p class="float-left otp-label">Enter OTP</p>
              <p class="float-right otp-fields">
                <%= text_field_tag 'otp[0]', nil, class: "otp-field", maxlength: 1, autocomplete: "off", required: true %>
                <%= text_field_tag 'otp[1]', nil, class: "otp-field", maxlength: 1, autocomplete: "off", required: true %>
                <%= text_field_tag 'otp[2]', nil, class: "otp-field", maxlength: 1, autocomplete: "off", required: true %>
                <%= text_field_tag 'otp[3]', nil, class: "otp-field", maxlength: 1, autocomplete: "off", required: true %>
              </p>
            </div>
          </div>
          
          <div class="field set-password">
            <% if User.minimum_password_length %>
              <em>(<%= User.minimum_password_length %> characters minimum)</em><br />
            <% end %>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text left-input-group-text">Set Password :</span>
              </div>
              <%= f.password_field :password, autocomplete: "new-password", placeholder: "New Password", required: true, class: "form-control signup-password-field" %>
              <div class="input-group-append">
                <span id="set-password-visibility" class="input-group-text right-input-group-text">
                  <%= image_tag "visibility.svg", class: "change-visibility make-visibile" %>
                  <%= image_tag "visibility-off.svg", class: "change-visibility make-invisibile" %>
                </span>
              </div>
            </div>
          </div>

          <div class="field confirm-password">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text left-input-group-text">Confirm Password :</span>
              </div>
              <%= f.password_field :confirm_password, autocomplete: "new-password", placeholder: "Confirm Password", required: true, class: "form-control signup-password-field" %>
              <div class="input-group-append">
                <span id="confirm-password-visibility" class="input-group-text right-input-group-text">
                  <%= image_tag "visibility.svg", class: "change-visibility make-visibile" %>
                  <%= image_tag "visibility-off.svg", class: "change-visibility  make-invisibile" %>
                </span>
              </div>
            </div>
          </div>
          <%= f.hidden_field :email_id, readonly: true %>
          <%= hidden_field_tag :step, @step %>
        <% else %>
          <%= f.email_field :email_id, autofocus: true, autocomplete: "email", placeholder: "E-mail", required: true %>
        <% end %>

        <div class="field field-right">
          <%= f.submit button_name, class: "submit_button" %>
        </div>
        
        <div class="field field-center login-link-margin">
          <%= link_to "Existing User? LOGIN", login_user_index_path, class: "light-red bold-text login-link" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  function validate(e){
    flag = true;
    if($('.otp-field').length > 0){
      $('.otp-field').each(function(index) {
        if($(this).val() == ""){
          flag = false;
          $(this).css("border", "1px solid red");
        };
      });
    }
    if($('#user_password').val() == ""){
      flag = false;
      $('#user_password').css("border", "1px solid red");
    }
    if($('#user_password').val() == ""){
      flag = false;
      $('#user_confirm_password').css("border", "1px solid red");
    }
    return flag;
  }
  
  <% if session[:otp].present? %>
    window.onload = function() {
      <% sent_time_in_rails = (session[:otp]["sent_time"].present? ? session[:otp]["sent_time"].to_time : Time.now.to_time).to_s.slice(0, 19) %>  
      <% if @step.to_sym == :otp_send || @step.to_sym == :password_not_match %>
        var x;
        clearInterval(x);
        start('<%= sent_time_in_rails %>');
      <% end %>
    };
  <% end %>

  function change_time(sent_time_in_rails){
    var sec_timer = document.getElementById("sec-timer");
    var time_holder = document.getElementById("time-holder");
    var sec_time;
    if(sec_timer != null){
      var sent_time = new Date(sent_time_in_rails)
      var time_diff = parseInt((new Date() - sent_time)/1000);
      var sec_time = parseInt(sec_timer.innerHTML);
      if((sec_time <= 0) && (120 - time_diff <= 0)){
        clearInterval(x);
        time_holder.innerHTML = '<%= link_to t(:resend_otp), resend_otp_user_index_path, remote: true %>';
        $(time_holder).find('a').attr("href", $(time_holder).find('a').attr("href") + "?email_id=" + $('#user_email_id').val());
      }else{
        if((120 - time_diff) > sec_time + 5){
          sec_time = 120 - time_diff;
        }else{
          sec_time = sec_time - 1;
        }
        sec_timer.innerHTML = sec_time;
      }
    }
  }
  
  function start(sent_time_in_rails){
    x = setInterval(function(){
      change_time(sent_time_in_rails)
    }, 1000);
  }
  
  $('body').delegate('.change-visibility', 'click', function(){
    var class_array = $(this).attr("class").split(" ");
    var parent_id = $(this).parent().attr("id");
    $(this).css("display", "none");
    if(jQuery.inArray("make-visibile", class_array) !== -1){
      $(`.${parent_id.replace("-visibility", "")} input`).attr("type", "text");
      $(`#${parent_id} .make-invisibile`).css("display", "block");
    }else{
      $(`.${parent_id.replace("-visibility", "")} input`).attr("type", "password");
      $(`#${parent_id} .make-visibile`).css("display", "block");
    }
  });
</script>