config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :user do
    collection do
      get :login
      post :login
      get :sign_up
      post :sign_up
      get :logout
      get :dashboard
      get :resend_otp
      get :forgot_password
      post :forgot_password
      patch :forgot_password
      post :register_as_seller
      get :register_as_seller
      patch :register_as_seller
      get :complete_signup
      patch :complete_signup
    end
  end

  resources :products do
    collection do
      get :sell_art
    end
  end

  constraints subdomain: 'admin' do
    get '/', to: 'arts#index'
  end

  root 'arts#index'
end

app/models/address.rb
class Address < ApplicationRecord
  serialize :address
  belongs_to :user_detail
  before_create :set_slug
  
  private
    def set_slug
      def set_slug
        time =Time.now.localtime
        slug = "ADD#{(rand(10 ** 5)).to_s.rjust(5, '0')}"
        while(Address.exists?(slug: slug))
          slug = "ADD#{(rand(10 ** 5)).to_s.rjust(5, '0')}"
        end
        self.slug = slug
      end
    end
end

app/models/art_era.rb
class ArtEra < ApplicationRecord

  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products
  has_many :subcategories
  has_many :minorcategories, through: :subcategories
  accepts_nested_attributes_for :subcategories
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
end

app/models/material.rb
class Material < ApplicationRecord

  has_many :products

end

app/models/medium.rb
class Medium < ApplicationRecord

  has_many :products

end

app/models/minorcategory.rb
class Minorcategory < ApplicationRecord
  
  belongs_to :subcategory, inverse_of: :minorcategories

  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: [ :subcategory_id] }
end

app/models/order.rb
require 'securerandom'
class Order < ApplicationRecord
  belongs_to :user_detail
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
  before_create :set_slug
  
  private
    def set_slug
      time =Time.now.localtime
      slug = "OD#{time.year}#{time.month}#{time.day}#{(rand(10 ** 10)).to_s.rjust(10, '0')}"
      while(Order.exists?(slug: slug))
        slug = "OD#{time.year}#{time.month}#{time.day}#{(rand(10 ** 10)).to_s.rjust(10, '0')}"
      end
      self.slug = slug
    end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :buyer, class_name: "UserDetail", foreign_key: :buyer_id
  belongs_to :seller, class_name: "UserDetail", foreign_key: :buyer_id
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :medium, optional: true
  belongs_to :material, optional: true
  belongs_to :art_era, optional: true
  has_many :product_details, dependent: :destroy
  has_many :stocks, through: :product_details
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products, dependent: :destroy
  # mount_uploaders :images, ImageUploader
  before_create :set_slug
  
  private
    def set_slug
      time =Time.now.localtime
      slug = "P#{time.year}#{time.month}#{time.day}#{(rand(10 ** 10)).to_s.rjust(10, '0')}"
      while(Product.exists?(slug: slug))
        slug = "P#{time.year}#{time.month}#{time.day}#{(rand(10 ** 10)).to_s.rjust(10, '0')}"
      end
      self.slug = slug
    end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord

  belongs_to :product
  belongs_to :size
  has_many :stocks

end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord

  belongs_to :product_detail
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :minorcategories

  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :category_id }
  accepts_nested_attributes_for :minorcategories, reject_if: :all_blank, allow_destroy: true

  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_detail, dependent: :destroy
  has_many :products
  delegate :full_name, :phone_no, to: :user_detail, allow_nil: true
  
  attr_accessor :password, :confirm_password, :dont_validate_password
  validates_presence_of :email_id
  validates_presence_of :password, if: Proc.new{|user| user.dont_validate_password != false}
  validates_presence_of :confirm_password, if: Proc.new{|user| user.new_record?}
  validate :password_match, if: Proc.new{|user| user.password.present?}
  validates :email_id, uniqueness: { scope: :is_active,
      message: "can have only one active per time." }, if: Proc.new{|user| user.new_record?} #:phone_no
  before_save :hash_password, if: Proc.new{|user| user.dont_validate_password != false}
   
  scope :active, -> { where(is_active: true) }
  
  
  def authenticate
    user = User.active.where("email_id = ?", self.email_id).first
    if user.present?
      return user.hashed_password == Digest::SHA1.hexdigest(user.password_salt.to_s + self.password)
    end
    return false
  end
  
  def send_otp_by_mail(otp)
    UserMailer.with(user: self, otp: otp).send_otp.deliver_now
  end
  
  def send_password_reset_token_by_mail
    if self.update(reset_password_token: SecureRandom.base64(17).gsub(/[+, =, \/]/,""), dont_validate_password: false)
      UserMailer.with(user: self).send_password_reset_token.deliver_now
    end
  end
  
  def self.minimum_password_length
    false
  end
  
  private
  
    def password_match
      if password != confirm_password
        errors.add(:password, "doesn't match")
      end
    end
    
    def hash_password
      self.password_salt =  SecureRandom.base64(8) if self.password_salt == nil
      self.hashed_password = Digest::SHA1.hexdigest(self.password_salt + self.password)
    end
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
  has_attached_file :avatar, default_url: "user-icons/common.svg"
  has_many :orders
  has_many :buy_order_products, class_name: "OrderProduct", foreign_key: :buyer_id
  has_many :buy_products, through: :buy_order_products, source: :product
  has_many :selling_order_products, class_name: "OrderProduct", foreign_key: :seller_id
  has_many :selling_products, through: :selling_order_products, source: :product
  has_many :addresses
  delegate :email_id, to: :user
  
  validates_presence_of :phone_no, :full_name
  validates :phone_no, numericality: true, length: { minimum: 10, maximum: 10 }
  after_create :update_phone_no_or_email_id
  
  def user_order_products_by_type(type = nil, page = nil)
    order_products = case type
      when "cancelled"
        buy_order_products.where(is_canceled: true)
      when "returns"
        buy_order_products.where(is_return: true)
      else
        buy_order_products.where(is_canceled: false)
        # buy_order_products.where(is_canceled: false, is_return: false)
      end
    order_products
  end
  
  private
    def update_phone_no_or_email_id
      self.user.update(phone_no: self.phone_no, dont_validate_password: false)
    end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:blue_notice].present? %>
  <div class="alert alert-primary" role="alert">
    <%= flash[:blue_notice].html_safe %>
  </div>
<% end %>
<% if flash[:lightgrey_notice].present? %>
  <div class="alert alert-secondary" role="alert">
    <%= flash[:lightgrey_notice].html_safe %>
  </div>
<% end %>
<% if flash[:success].present? %>
  <div class="alert alert-success" role="alert">
    <%= flash[:success].html_safe %>
  </div>
<% end %>
<% if flash[:danger].present? %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:danger].html_safe %>
  </div>
<% end %>
<% if flash[:warning].present? %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:warning].html_safe %>
  </div>
<% end %>
<% if flash[:info].present? %>
  <div class="alert alert-info" role="alert">
    <%= flash[:info].html_safe %>
  </div>
<% end %>
<% if flash[:light].present? %>
  <div class="alert alert-light" role="alert">
    <%= flash[:light].html_safe %>
  </div>
<% end %>
<% if flash[:dark].present? %>
  <div class="alert alert-dark" role="alert">
    <%= flash[:dark].html_safe %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Getart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-container fixed-top bg-white">
      <nav class="navbar navbar-expand-md navbar-light fixed-top bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "Get Art", root_path, class: "navbar-brand get-art col-7" %>
        <div class="collapse navbar-collapse col-5" id="navbarCollapse">
          <form class="form-inline mt-2 mt-md-0">
            <div class="search-icon"><%= fa_icon('search') %></div>
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </form>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <% link_name = @current_user && @current_user.user_detail.id ? @current_user.user_detail.full_name.titleize : "My Account" %>
              <%= link_to link_name, dashboard_user_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "#", :class=> "nav-link" do %>
              <%= fa_icon('heart') %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "#", :class=> "nav-link" do %>
              <%= fa_icon('shopping-cart') %>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="main-container">
      <%= breadcrumbs separator: " &rsaquo; " %>
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="quote">
        <blockquote class="blockquote mb-0">
          <p class="text-muted font-italic">"Art washes away from the soul the dus of everyday life."</p>
         <footer class="blockquote-footer"> <cite title="Source Title">Pablo Picaso</cite></footer>
        </blockquote>
      </div>
      <div class="footer-detail">
        <div class="row">
          <div class="col-4">
            <h5 class="footer-heading">Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
            </ul>
          </div>
          <div class="col-4">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-4">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>